name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: true
      - name: Install Dependencies
        run: apt-key adv --keyserver gpg.mit.edu --recv-keys 1AD28806 &&
             sh -c 'echo deb https://www.charlesproxy.com/packages/apt/ charles-proxy main > /etc/apt/sources.list.d/charles.list' &&
             apt-get update &&
             apt-get install charles-proxy &&
             apt-get install libnss3-tools &&
             brew install mkcert
      - name: Test
        run: charles --help
