name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: true
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Dependencies
        run: wget -q -O - https://www.charlesproxy.com/packages/apt/PublicKey | sudo apt-key add - &&
             sudo sh -c 'echo deb https://www.charlesproxy.com/packages/apt/ charles-proxy main > /etc/apt/sources.list.d/charles.list' &&
             sudo apt-get update &&
             sudo apt-get install charles-proxy libnss3-tools &&
             brew install mkcert
      - name: set-up charles (currently uneeded)
        run: rsync -av --exclude=.actions/charles/.config/* .actions/charles/.config/ ~/ &&
             rsync -av --exclude=.actions/charles/.charles/* .actions/charles/.charles/ ~/
      - name: set-up shopdeck
        run: python -m pip install -r requirements.txt &&
             
             
