name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: true
      - name: Install Dependencies
        run: wget -q -O - https://www.charlesproxy.com/packages/apt/PublicKey | sudo apt-key add - &&
             sudo sh -c 'echo deb https://www.charlesproxy.com/packages/apt/ charles-proxy main > /etc/apt/sources.list.d/charles.list' &&
             sudo apt-get update &&
             sudo apt-get install charles-proxy &&
             sudo apt-get install libnss3-tools &&
             brew install mkcert
      - name: Test
        run: charles --help
